<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEse4733\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEse4733/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerEse4733.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerEse4733\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerEse4733\appProdProjectContainer([
    'container.build_hash' => 'Ese4733',
    'container.build_id' => 'b934e7df',
    'container.build_time' => 1593631324,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEse4733');
